# Dependencies
#markdown:         kramdown
#highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Signiant Developer
tagline:          ''
description:      'Accelerating file transfers'
url:              http://dev.signiant.com
baseurl:          /

author:
  name:           'Signiant'
  url:            https://twitter.com/signiant

# Custom vars
version:          2.5.2 #the current version of the JavaScript Transfer API

github:
  repo:           https://github.com/Signiant
  
include: ['_pages']