# Dependencies
#markdown:         kramdown
#highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Signiant Developer
tagline:          ''
description:      'The Signiant Developer Website'
url:              http://signiant.github.io/
baseurl:          /web-transfer-api-samples/

author:
  name:           'Signiant'
  url:            https://twitter.com/signiant

# Custom vars
version:          2.5.2

github:
  repo:           https://github.com/Signiant
  
include: ['_pages']